language: node_js
node_js:
  - "8"
  - "10"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.24.3
  - export PATH="$HOME/.yarn/bin:$PATH"
before_script:
  - yarn
script: yarn test
cache: yarn
